module ActionCable
  module Channel
    module Broadcasting
      extend ActiveSupport::Concern

      module ClassMethods
        # Broadcast a hash to a unique broadcasting for this <tt>model</tt> in this channel.
        def broadcast_to: (untyped model, untyped message) -> untyped

        # Returns a unique broadcasting identifier for this <tt>model</tt> in this channel:
        #
        #    CommentsChannel.broadcasting_for("all") # => "comments:all"
        #
        # You can pass any object as a target (e.g. Active Record model), and it
        # would be serialized into a string under the hood.
        def broadcasting_for: (untyped model) -> untyped

        def serialize_broadcasting: (untyped object) -> untyped
      end
    end
  end
end
