AllCops:
  NewCops: enable
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# frozen_string_literal: trueを無くす
Style/FrozenStringLiteralComment:
  Enabled: false

# メソッド名に数字を許可
Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false
