interface _RbsRailsPathHelpers
  def rails_info_properties_path: (*untyped) -> String
  def rails_info_routes_path: (*untyped) -> String
  def rails_info_path: (*untyped) -> String
  def health_check_path: (*untyped) -> String
  def api_v1_users_path: (*untyped) -> String
  def api_v1_user_path: (*untyped) -> String
  def api_v1_me_path: (*untyped) -> String
  def api_v1_plan_svgs_path: (*untyped) -> String
  def api_v1_plan_roles_path: (*untyped) -> String
  def api_v1_role_path: (*untyped) -> String
  def api_v1_plan_members_path: (*untyped) -> String
  def api_v1_member_path: (*untyped) -> String
  def api_v1_map_svgs_path: (*untyped) -> String
  def api_v1_svg_path: (*untyped) -> String
  def api_v1_plan_maps_path: (*untyped) -> String
  def api_v1_map_path: (*untyped) -> String
  def api_v1_plan_todo_lists_path: (*untyped) -> String
  def api_v1_todo_list_path: (*untyped) -> String
  def api_v1_plans_path: (*untyped) -> String
  def api_v1_plan_path: (*untyped) -> String
  def rails_service_blob_path: (*untyped) -> String
  def rails_blob_representation_path: (*untyped) -> String
  def rails_disk_service_path: (*untyped) -> String
  def update_rails_disk_service_path: (*untyped) -> String
  def rails_direct_uploads_path: (*untyped) -> String
  def rails_representation_path: (*untyped) -> String
  def rails_blob_path: (*untyped) -> String
  def rails_info_properties_url: (*untyped) -> String
  def rails_info_routes_url: (*untyped) -> String
  def rails_info_url: (*untyped) -> String
  def health_check_url: (*untyped) -> String
  def api_v1_users_url: (*untyped) -> String
  def api_v1_user_url: (*untyped) -> String
  def api_v1_me_url: (*untyped) -> String
  def api_v1_plan_svgs_url: (*untyped) -> String
  def api_v1_plan_roles_url: (*untyped) -> String
  def api_v1_role_url: (*untyped) -> String
  def api_v1_plan_members_url: (*untyped) -> String
  def api_v1_member_url: (*untyped) -> String
  def api_v1_map_svgs_url: (*untyped) -> String
  def api_v1_svg_url: (*untyped) -> String
  def api_v1_plan_maps_url: (*untyped) -> String
  def api_v1_map_url: (*untyped) -> String
  def api_v1_plan_todo_lists_url: (*untyped) -> String
  def api_v1_todo_list_url: (*untyped) -> String
  def api_v1_plans_url: (*untyped) -> String
  def api_v1_plan_url: (*untyped) -> String
  def rails_service_blob_url: (*untyped) -> String
  def rails_blob_representation_url: (*untyped) -> String
  def rails_disk_service_url: (*untyped) -> String
  def update_rails_disk_service_url: (*untyped) -> String
  def rails_direct_uploads_url: (*untyped) -> String
  def rails_representation_url: (*untyped) -> String
  def rails_blob_url: (*untyped) -> String
end
