class PlanChannel < ApplicationCable::Channel
  def subscribed: () -> void

  def unsubscribed: () -> void

  def toggleTodoStatus: (Hash req) -> void

  def beginPlan: (Hash req) -> void

  def endPlan: (Hash req) -> void

  def sendActiveSvg: (Hash req) -> void
end
