class PlanChannel < ApplicationCable::Channel
  def subscribed: () -> void

  def unsubscribed: () -> void

  def toggle_todo_status: (Hash hash) -> void

  def begin_plan: () -> void

  def end_plan: () -> void
end
