development:
  adapter: redis
  host: 'redis'
  channel_prefix: api_development

test:
  adapter: test

production:
  adapter: redis
  host: <%= Rails.application.credentials.dig(:redis, :host)%>
  channel_prefix: api_production
