module Api
  module V1
    class ApplicationController < ActionController::API
      include Firebase::Auth::Authenticable

      include Api::ExceptionHandler

      include Api::FirebaseAuth

      def response_success: (untyped attr) -> void

      private
      def snakeize_params: -> untyped
    end
  end
end
