module Api
  module V1
    class ApplicationController < ActionController::API
      include Firebase::Auth::Authenticable

      include Api::ExceptionHandler

      include Api::FirebaseAuth
    end
  end
end
