module Api
  module V1
    class UsersController < ApplicationController
      extend ActiveRecord::SpawnMethods

      def show: () -> untyped

      def create: () -> untyped

      def update: () -> untyped

      def destroy: () -> untyped

      def me: () -> void

      private

      def user_params: () -> untyped

      def sign_in_provider: () -> String
    end
  end
end
